#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RehberLinqtoSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="veriler1")]
	public partial class RehberClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertrehber(rehber instance);
    partial void Updaterehber(rehber instance);
    partial void Deleterehber(rehber instance);
    #endregion
		
		public RehberClasses1DataContext() : 
				base(global::RehberLinqtoSql.Properties.Settings.Default.veriler1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RehberClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RehberClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RehberClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RehberClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<rehber> rehber
		{
			get
			{
				return this.GetTable<rehber>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rehber")]
	public partial class rehber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Adsoyad;
		
		private string _Eposta;
		
		private string _Sehir;
		
		private string _Adres;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _Ktarihi;
		
		private string _Telno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAdsoyadChanging(string value);
    partial void OnAdsoyadChanged();
    partial void OnEpostaChanging(string value);
    partial void OnEpostaChanged();
    partial void OnSehirChanging(string value);
    partial void OnSehirChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnKtarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnKtarihiChanged();
    partial void OnTelnoChanging(string value);
    partial void OnTelnoChanged();
    #endregion
		
		public rehber()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adsoyad", DbType="NVarChar(25)")]
		public string Adsoyad
		{
			get
			{
				return this._Adsoyad;
			}
			set
			{
				if ((this._Adsoyad != value))
				{
					this.OnAdsoyadChanging(value);
					this.SendPropertyChanging();
					this._Adsoyad = value;
					this.SendPropertyChanged("Adsoyad");
					this.OnAdsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eposta", DbType="NVarChar(50)")]
		public string Eposta
		{
			get
			{
				return this._Eposta;
			}
			set
			{
				if ((this._Eposta != value))
				{
					this.OnEpostaChanging(value);
					this.SendPropertyChanging();
					this._Eposta = value;
					this.SendPropertyChanged("Eposta");
					this.OnEpostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(30)")]
		public string Sehir
		{
			get
			{
				return this._Sehir;
			}
			set
			{
				if ((this._Sehir != value))
				{
					this.OnSehirChanging(value);
					this.SendPropertyChanging();
					this._Sehir = value;
					this.SendPropertyChanged("Sehir");
					this.OnSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(50)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(400)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ktarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ktarihi
		{
			get
			{
				return this._Ktarihi;
			}
			set
			{
				if ((this._Ktarihi != value))
				{
					this.OnKtarihiChanging(value);
					this.SendPropertyChanging();
					this._Ktarihi = value;
					this.SendPropertyChanged("Ktarihi");
					this.OnKtarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telno", DbType="NVarChar(15)")]
		public string Telno
		{
			get
			{
				return this._Telno;
			}
			set
			{
				if ((this._Telno != value))
				{
					this.OnTelnoChanging(value);
					this.SendPropertyChanging();
					this._Telno = value;
					this.SendPropertyChanged("Telno");
					this.OnTelnoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
